add scale option
openseadragon/html-overlay pull request #2
Opened 2021-08-27 19:57 UTC by altert

Adds scale option. To add HTML overlay with scaling to your OpenSeadragon Viewer, call htmlOverlay({scale: scaleWidth}).
This is useful in case the width of tileSource is not set, or you want html overlay dimensions to be independent of image dimensions. By default scale is set to 1 for backwards compatibility or cases where tileSource width is set.

2021-08-30 18:38 UTC, iangilman requested changes
Looks great! I've tested it and it seems to work well. 

Can you please update the README to document this new feature? It might be helpful to give an example so people know what kind of numbers to use. 

Can you also update the changelog? 

Thank you!

2021-08-30 18:38 UTC, iangilman commented on openseadragon-html-overlay.js
> +// OpenSeadragon HTML Overlay plugin 0.0.2
Thank you for bumping the version number here. Can you do it in the package.json as well?

2021-08-30 18:38 UTC, iangilman commented on openseadragon-html-overlay.js
> +    $.Viewer.prototype.htmlOverlay = function(options) {
I suppose it doesn't make that big of a difference, but the pattern I like for this is:

```
$.Viewer.prototype.htmlOverlay = function(options) {
  options = options || {};
```

That way if we end up adding more options we won't have to keep checking for the existence of the options object.

2021-08-30 18:38 UTC, iangilman commented on openseadragon-html-overlay.js
> +            this._htmlOverlayInfo._scale = options.scale; // arbitrary scale for created fabric canvas
In this comment it should be "overlay element" or something rather than "fabric canvas".

2021-08-30 19:38 UTC, altert commented
added requested changes, updated demo to include version that uses `scale` option

2021-08-31 18:30 UTC, iangilman approved these changes
Fantastic! Thank you :)

2021-08-31 18:30 UTC, merged

2021-08-31 18:56 UTC, iangilman commented
I made some changes to the README and the demo file... I hope you don't mind!

https://github.com/openseadragon/html-overlay/commit/7b13d60a7cde11a8e68f654148976bcffe8292db

Thanks again for making this patch :)